import 'package:quizapp/mcq.dart';

List<MCQ> allQuestions = [
  MCQ(
    question:
        "intellectual midwifery is the theory of knowledge put forward by:",
    answer: "d",
    option1: "Plato",
    option2: "Thales",
    option3: "Comte",
    option4: "Socrates",
  ),
  MCQ(
    question: "______ is a Skeptic",
    answer: "a",
    option1: "David Hume",
    option2: "Emmanuel Kant",
    option3: "Hegel",
    option4: "None of these",
  ),
  MCQ(
    question: "The theory that holds reason as the source of knowledge is",
    answer: "b",
    option1: "Idealism",
    option2: "Rationalism",
    option3: "Empiricism",
    option4: "None of the above",
  ),
  MCQ(
    question: " The founder of Positivism is",
    answer: "c",
    option1: " Saint Simon",
    option2: "C. S Pierce",
    option3: "August Comte",
    option4: "Francis Bacon",
  ),
  MCQ(
    question: "The science of values is known as ",
    answer: "10",
    option1: "Axiology",
    option2: "Sociology",
    option3: "Ontology",
    option4: "Cosmology",
  ),
  MCQ(
    question: "Metaphysics is the work of ",
    answer: "c",
    option1: "Socrates",
    option2: "Plato",
    option3: "Aristotle",
    option4: "Thales",
  ),
  MCQ(
    question: "Early Skepticism is also known as ",
    answer: "a",
    option1: "pyrrhonism",
    option2: "Positivism",
    option3: "Materialism",
    option4: "Idealism",
  ),
  MCQ(
    question: " epistemology studies",
    answer: "d",
    option1: "Origin and Nature of knowledge",
    option2: "Validity of knowledge",
    option3: "Extend of knowledge",
    option4: "All of the above",
  ),
  MCQ(
    question: "The two branches of Metaphysics are",
    answer: "c",
    option1: "Religion and Theology",
    option2: "Rationalism and Empiricism",
    option3: "Ontology and Cosmology",
    option4: "Materialism and Spiritualism",
  ),
  MCQ(
    question: "Philosophy is concerned with ",
    answer: "c",
    option1: "The irrational ",
    option2: "Beauty",
    option3: "The ideal",
    option4: "experimentation",
  ),
  MCQ(
    question:
        "The four main divisions of philosophy are metaphysics, epistemology, axiology, and _____.",
    answer: "b",
    option1: "bioethics",
    option2: "logic",
    option3: "aesthetics",
    option4: "categorical logic",
  ),
  MCQ(
    question:
        " A question-and-answer dialogue in which propositions are methodically scrutinized to uncover the truth is known as _____.",
    answer: "b",
    option1: " an argument",
    option2: "the Socratic method",
    option3: "the Socratic jest",
    option4: " a debate",
  ),
  MCQ(
    question:
        "If you assume that a set of statements is true, and yet you can deduce a false or absurd statement from it, then the original set of statements as a whole must be false. This kind of argument is known as _____.",
    answer: "d",
    option1: "modus tollens",
    option2: "modus ponens",
    option3: "hypothetical syllogism",
    option4: "reductio ad absurdum",
  ),
  MCQ(
    question:
        "The systematic use of critical reasoning to try to find answers to fundamental questions about reality, morality, and knowledge is called _____.",
    answer: "b",
    option1: "the argumentative method",
    option2: "the philosophical method",
    option3: "propositional logic",
    option4: "syllogistic reasoning",
  ),
  MCQ(
    question:
        "The study of reality in the broadest sense, an inquiry into the elemental nature of the universe and the things in it, is known as _____.",
    answer: "a",
    option1: "metaphysics",
    option2: "epistemology",
    option3: "quantum physics",
    option4: "axiology",
  ),
  MCQ(
    question:
        "Questions like “What is knowledge?” and “What is truth?” are mainstays in the branch of philosophy known as _____.",
    answer: "c",
    option1: "logic",
    option2: "metaphysics",
    option3: "epistemology",
    option4: "aesthetics",
  ),
  MCQ(
    question: "A moral theory explains _____.",
    answer: "a",
    option1: "why an action is right or wrong",
    option2: "why one moral event caused another",
    option3: "where a moral agent got her values",
    option4: "why people do what they do",
  ),
  MCQ(
    question:
        "Descartes says that the chief characteristic of physical things is that _____.",
    answer: "d",
    option1: " they cannot be measured",
    option2: "science can study them",
    option3: "they do not have extension",
    option4: "they have extension",
  ),
  MCQ(
    question:
        "Darwin’s primary contribution to biological theory was the idea that",
    answer: "a",
    option1:
        "an important mechanism of biological evolution is natural selection",
    option2: "new alleles arise through mutation",
    option3: "evolution is the change in gene frequencies over time",
    option4: "genes are the units of inheritance",
  ),
  MCQ(
    question:
        "Which statement best represents the meaning of the term evolution:",
    answer: "b",
    option1: "Changes in species toward greater complexity over time",
    option2: "Changes in gene frequencies in a population over time",
    option3: "The strongest individuals survive and produce the most offspring",
    option4:
        "Changes in an individual over time in response to natural selection",
  ),
  MCQ(
    question:
        "Over the past several decades, natural selection has caused populations of Staphylococcus aureus (an infectious wound bacterium) to evolve resistance to most antibiotics. If antibiotic use were stopped, what would you predict would happen to these S. aureus populations?",
    answer: "d",
    option1: "They will go extinct without the antibiotic.",
    option2:
        "The frequency of resistant forms will increase in these populations.",
    option3: "The populations will begin colonizing new environments.",
    option4:
        "The frequency of nonresistant forms will increase in these populations.",
  ),
  MCQ(
    question:
        "Which of the following are NOT found as preserved traces of plants or animals?",
    answer: "a",
    option1: "skin",
    option2: "footprints",
    option3: "burrows",
    option4: "rootlet traces",
  ),
  MCQ(
    question:
        "Natural selection occurs because organisms within a particular species have...",
    answer: "a",
    option1: "variation due to differences in their genes",
    option2: "the ability to change colour to suit the background",
    option3:
        "the ability to pass on characteristics acquired over their lifetime",
    option4: "fewer offspring than are able to survive",
  ),
  MCQ(
    question:
        "Which scientist believed that evolution happened when organisms passed on characteristics they had acquired during their lifetime?",
    answer: "a",
    option1: "Lamarck",
    option2: "Wallace",
    option3: "Darwin",
    option4: "Pasteur",
  ),
  MCQ(
    question:
        "Which of the following is NOT a way in which fossils are formed?",
    answer: "a",
    option1: "from the soft parts of animals",
    option2: "when the conditions needed for decay are absent",
    option3: "	when parts of the animal are replaced by other materials",
    option4: "from the hard parts of animals",
  ),
  MCQ(
    question: "Successful organisms pass on characteristics because... ",
    answer: "c",
    option1: "	they survive and breed",
    option2: "they are less likely to die of a disease",
    option3: "they survive, breed and pass on genes",
    option4: "they are more successful at competing",
  ),
  MCQ(
    question: "In \"survival of the fittest\" - the fittest organisms are...",
    answer: "c",
    option1: "the ones that can run the fastest",
    option2: "the largest organisms",
    option3: "the best adapted to their environment",
    option4: "the ones that can produce the most offspring",
  ),
  MCQ(
    question: "On the Origin of Species was written by ______",
    answer: "a",
    option1: "Charles Darwin",
    option2: "Ludmila Kuprianova",
    option3: "Mikhail A. Fedonkin",
    option4: "Ituhbuna Lawraga",
  ),
  MCQ(
    question: "The force that initiates evolution is ______",
    answer: "a",
    option1: "Variation",
    option2: "Mutation",
    option3: "Extinction",
    option4: "Adaptation",
  ),
  MCQ(
    question: "Charles Darwin was best known in the 19th century for:",
    answer: "c",
    option1: "creating the idea of evolution",
    option2: "creating the idea of uniformitarianism",
    option3:
        "making the idea of evolution acceptable for scientists and the educated general public",
    option4: "all of the above",
  ),
  MCQ(
    question:
        "Charles Darwin concluded that the 13 species of finches on the Galápagos Islands:",
    answer: "b",
    option1:
        "were identical to 13 finch species in northwestern South America 600 miles to the east",
    option2: "probably evolved from one ancestral South American species",
    option3: "had all adapted to the same food sources",
    option4: "B and C",
  ),
  MCQ(
    question:
        "Through careful observation, Charles Darwin came to understand that:",
    answer: "b",
    option1:
        "populations of plants and animals in nature most often consist of individuals that are clones of each other",
    option2:
        "those individuals whose variation gives them an advantage in staying alive long enough to reproduce are more likely to pass their traits on to the next generation",
    option3:
        "populations of a species that become isolated from others by adapting to different environmental niches quickly become extinct",
    option4: "all of the above",
  ),
  MCQ(
    question: "Which of the following statements is true about Charles Darwin?",
    answer: "d",
    option1:
        "He believed that evolution was due to the inheritance of acquired characteristics.",
    option2: "He supported Lamarck's explanation of how evolution occurred.",
    option3:
        "He understood that the variation that exists in natural populations of plants or animals is the result of repeated mutations.",
    option4: "none of the above",
  ),
  MCQ(
    question:
        "The theory of evolution by natural selection was independently developed by:",
    answer: "b",
    option1: "Charles Lyell and Charles Darwin",
    option2: "Charles Darwin and Alfred Wallace",
    option3: "Erasmus Darwin and Lamarck",
    option4: "Charles Lyell and James Hutton",
  ),
  MCQ(
    question: "Philosophy deals with _________ of reality",
    answer: "b",
    option1: "a part ",
    option2: " the whole ",
    option3: " the illusion ",
    option4: "none of these",
  ),
  MCQ(
    question: "._________ is the inquiry into ‘being in general’. ",
    answer: "a",
    option1: "Ontology",
    option2: "Physics",
    option3: "Epistemology",
    option4: "Ethics",
  ),
  MCQ(
    question:
        "Coherence theory recognizes the relationship between ____________.",
    answer: "b",
    option1: " truth and validity",
    option2: "judgments within a system ",
    option3: "fact and judgment",
    option4: "all these ",
  ),
  MCQ(
    question: "Ontology is related to _______ as Ethics is to Axiology. ",
    answer: "d",
    option1: "Aesthetics",
    option2: "Cosmology",
    option3: "Idealism",
    option4: "Metaphysics",
  ),
  MCQ(
    question: "Ontology deals with ",
    answer: "c",
    option1: "Matter",
    option2: "Knowledge",
    option3: "Being",
    option4: "None of these",
  ),
  MCQ(
    question: "Berkeley argues that all knowledge is derived from ",
    answer: "b",
    option1: "Impression",
    option2: "Ideas",
    option3: "Axioms",
    option4: "Postulates",
  ),
  MCQ(
    question: ".The method of philosophy is ",
    answer: "a",
    option1: "Rational reflection ",
    option2: "Dogmatism",
    option3: "Emperical study",
    option4: "Revelation",
  ),
  MCQ(
    question: "Who said ? Philosophy is the Science of sciences",
    answer: "c",
    option1: "Plato",
    option2: "Voltaire",
    option3: "August Comte",
    option4: "Russell",
  ),
  MCQ(
    question:
        " ———— said “whatever is. Clearly and distinctly perceived is true",
    answer: "c",
    option1: "Locke",
    option2: "Berkeley",
    option3: "Descartes",
    option4: "None of these ",
  ),
  MCQ(
    question: ".According to Skepticism knowledge is ———-",
    answer: "c",
    option1: "Certain",
    option2: "Possible",
    option3: "Uncertain",
    option4: "None of these",
  ),
  MCQ(
    question: "For Idealism ——— is primary",
    answer: "a",
    option1: "Mind",
    option2: "Body",
    option3: "Perception",
    option4: "Sense experience",
  ),
  MCQ(
    question:
        "The problem of Universals was first introduced into philosophy by:",
    answer: "c",
    option1: "Aquinas",
    option2: "Aristotle",
    option3: "Plato",
    option4: "Berkeley",
  ),
  MCQ(
    question: "The father of philosophy :",
    answer: "b",
    option1: "Descartes",
    option2: "Thales",
    option3: "Aristotle",
    option4: "Francis Bacon",
  ),
  MCQ(
    question: "Who is the father of modern philosophy?",
    answer: "a",
    option1: "Descartes",
    option2: "Spinoza",
    option3: "Hobbes",
    option4: "Leibniz",
  ),
  MCQ(
    question:
        "The three main divisions of Philosophy are metaphysics, epistemology, and ———",
    answer: "a",
    option1: "Axiology",
    option2: "Sociology",
    option3: "Anthropology",
    option4: "Cosmology",
  ),
  MCQ(
    question: "A logical sentence is called ———",
    answer: "a",
    option1: "Proposition",
    option2: "Syllogism",
    option3: "Preposition",
    option4: "Clause",
  ),
  MCQ(
    question: "Descartes was a ———thinker",
    answer: "b",
    option1: "Emperical",
    option2: "Rational",
    option3: "Materialistic",
    option4: "Idealistic",
  ),
  MCQ(
    question:
        "Which American mathematician philosopher laid the foundation of Pragmatism",
    answer: "c",
    option1: "William James ",
    option2: " J. Dewey",
    option3: "C.S Pierce ",
    option4: "Spinoza",
  ),
  MCQ(
    question:
        "The study of the origin and development of the universe is known as———",
    answer: "b",
    option1: "Ontology",
    option2: "Cosmology",
    option3: "Zoology",
    option4: "Sociology",
  ),
  MCQ(
    question: "Who is the father of existentialism?",
    answer: "a",
    option1: "Soren Kierkegaard.",
    option2: "Camus",
    option3: "Sartre",
    option4: "Heidegger",
  ),
  MCQ(
    question: "Plato was the teacher of ———",
    answer: "a",
    option1: "Georgias",
    option2: "Socrates",
    option3: "Aristotle",
    option4: "Protogoras",
  ),
  MCQ(
    question: "———— is an Empiricist",
    answer: "d",
    option1: " Locke",
    option2: "Berkeley",
    option3: "Hume",
    option4: "all of these",
  ),
  MCQ(
    question: "The doubt of Descartes should not be confused with ———",
    answer: "a",
    option1: "Skepticism",
    option2: "Solipsism",
    option3: "Idealism",
    option4: "Intuitionism",
  ),
  MCQ(
    question: "Locke is a ———",
    answer: "d",
    option1: "Idealist",
    option2: "phenomenologist",
    option3: "Critical realist ",
    option4: "Representative realist",
  ),
  MCQ(
    question:
        "The philosophical area which deals with the problem of Being is called__________. ",
    answer: "d",
    option1: " Axiology",
    option2: "epistemology ",
    option3: "Materialism",
    option4: "ontology",
  ),
  MCQ(
    question: "________ rejected innate ideas.",
    answer: "b",
    option1: "Rene Descartes",
    option2: "John Locke",
    option3: "Spinoza",
    option4: "None of these ",
  ),
  MCQ(
    question:
        "Esse est percipi and Tabula rasa indicate the position of __________ respectively.",
    answer: "b",
    option1: " Locke and Hume",
    option2: "Berkeley and Locke",
    option3: "Berkeley and Hume",
    option4: "Descartes and Locke ",
  ),
  MCQ(
    question: "The theory of innate ideas was first propounded by______.",
    answer: "c",
    option1: "John Locke",
    option2: "Spinoza",
    option3: "Descartes",
    option4: "David Hume",
  ),
  MCQ(
    question: "________ argue that objects do not exist independent of mind. ",
    answer: "d",
    option1: "Materialists",
    option2: "Realists",
    option3: "Objectivists",
    option4: "Idealists ",
  ),
  MCQ(
    question: "Esse est Percipi is the dictum of _________ Idealism. ",
    answer: "b",
    option1: "Objective",
    option2: "Subjective",
    option3: "Absolute",
    option4: "All these ",
  ),
  MCQ(
    question: "Tabula rasa is the concept of _________.",
    answer: "c",
    option1: "Idealism",
    option2: "Cosmology",
    option3: "Empiricism",
    option4: "Pluralism",
  ),
  MCQ(
    question: "._______ is a representative of idealism",
    answer: "d",
    option1: "Carvakas ",
    option2: "Marx ",
    option3: "Engels",
    option4: " None of these ",
  ),
  MCQ(
    question: "Epistemology is concerned with ________ of knowledge.",
    answer: "d",
    option1: "origin",
    option2: "validity",
    option3: "limitation",
    option4: "All these ",
  ),
  MCQ(
    question: "Skeptics consider truth as _________.",
    answer: "c",
    option1: "certain ",
    option2: "necessary ",
    option3: "probable ",
    option4: "practical ",
  ),
  MCQ(
    question:
        "Charles Pierce, William James and John Dewy are prominent advocates of the _________ theory of truth",
    answer: "b",
    option1: "Coherence theory",
    option2: "Pragmatic theory ",
    option3: "Correspondence theory",
    option4: "None of these ",
  ),
  MCQ(
    question: "________ hold coherence theory.",
    answer: "d",
    option1: "Realists ",
    option2: "Idealists ",
    option3: " Both (a) and (b) ",
    option4: "Neither (a) nor (b)",
  ),
  MCQ(
    question: "John Dewey is a/an ________.",
    answer: "d",
    option1: "rationalist ",
    option2: "absolutist ",
    option3: "idealist",
    option4: "pragmatist",
  ),
  MCQ(
    question: "First Philosophy’ refers to __________.",
    answer: "b",
    option1: "Aesthetics ",
    option2: "Metaphysics ",
    option3: "Epistemology",
    option4: "Ethics ",
  ),
  MCQ(
    question: "__________ is the founder of Idealism. ",
    answer: "c",
    option1: "Hegel ",
    option2: "Spinoza ",
    option3: "Plato ",
    option4: "Aristotle",
  ),
  MCQ(
    question: "‘True knowledge is a priori’. This is the view of __________.",
    answer: "c",
    option1: "Empiricists ",
    option2: "Materialists ",
    option3: "Rationalists ",
    option4: " All these ",
  ),
  MCQ(
    question: "_________ is an area of applied ethics.",
    answer: "c",
    option1: "Metaethics ",
    option2: "Descriptive ethics ",
    option3: "Cyber-ethics",
    option4: " None of these ",
  ),
  MCQ(
    question: "The study of philosophy stimulates ___________. ",
    answer: "b",
    option1: "dogmatism ",
    option2: " critical thinking ",
    option3: "blind faith ",
    option4: " All these",
  ),
  MCQ(
    question: " Why are the soft parts of a shark’s body not preserved as a fossil?",
    answer: "d",
    option1: "They are squeezed out when the shark is buried",
    option2: "They are not made of mineral or rock.",
    option3: "They cannot be changed to rock.",
    option4: "They rotted before fossilization could occur",
  ),
  MCQ(
    question:
        " Which would be an example of a fossil?",
    answer: "c",
    option1: "sedimentary rock",
    option2: "oyster pearl ",
    option3: "dinosaur footprint",
    option4: "rotting log",
  ),
  MCQ(
    question: " Which rock type would be best for ﬁnding fossils?",
    answer: "a",
    option1: "sedimentary",
    option2: "metamorphic",
    option3: "volcanic",
    option4: "igneous",
  ),
  MCQ(
    question:
        "What is a common cause of plant and animal extinction?",
    answer: "a",
    option1: "The climate changes.",
    option2: "They die out from over-eating.",
    option3: "They run out of homes to live in",
    option4: "They are trapped and moved.",
  ),
  MCQ(
    question: "Which of the following could be a fossil?",
    answer: "d",
    option1: "a woman who lived 15,000 years ago found frozen in a glacier ",
    option2: "a penguin that lived 100,000 years ago found in a dry valley in Antarctica",
    option3: "a wasp inside a 30 million year old block of amber",
    option4: "all of the above",
  ),
  MCQ(
    question: "Which of the following statements is true about fossilization?",
    answer: "d",
    option1: "It is a common occurrence.",
    option2: "It is more common for animals from mountains and forests than for those from deserts and oceans.",
    option3: "Small animals with light weight, thin bones are more likely to become fossils than are large animals with heavy, dense bones.",
    option4: "none of the above",
  ),
  MCQ(
    question: "The body of an animal is more likely to become fossilized if it:",
    answer: "a",
    option1: "is buried deeply in the ground",
    option2: "is left on the surface of the ground",
    option3: "does not contain bones or other hard body parts ",
    option4: "all of the above are about equally likely to result in fossilization",
  ),
  MCQ(
    question: "Which of the following statements is true?",
    answer: "a",
    option1: "The bones of living animals normally contain both organic molecules and inorganic minerals.",
    option2: "The fossil record for all continents is now equally well understood.",
    option3: "Ground water percolating down through the soil is usually a hindrance to the mineralization of buried bone.",
    option4: "none of the above",
  ),
  MCQ(
    question: "Which of the following can be learned about a species from studying their fossilized skeletons?",
    answer: "d",
    option1: "growth patterns ",
    option2: "life expectancy ",
    option3: "medical pathologies",
    option4: "all of the above",
  ),
  MCQ(
    question: "Which of the following statements is true of the fossil record?",
    answer: "a",
    option1: "Our interpretation of the fossil record has been biased.",
    option2: "The data for paleoanthropology come mainly from human genetics.",
    option3: "Amber is a form of mineralized bone.",
    option4: "The skeleton from La Chapelle-aux-Saints was from a typical young, healthy Neandertal man.",
  ),
  MCQ(
    question: "Which of the following forms when a fossil mold is filled?",
    answer: "d",
    option1: "petrified fossil ",
    option2: "tar pit ",
    option3: "carborn film",
    option4: "fossil cast ",
  ),
  MCQ(
    question:
        "For fossils to form, the remains must be covered quickly by ____________.",
    answer: "b",
    option1: "Coprolites",
    option2: "Sediment",
    option3: "Water",
    option4: "Scavengers",
  ),
  MCQ(
    question: "___________ is a cavity in rock made when an organism decayed.",
    answer: "b",
    option1: "cast ",
    option2: "mold ",
    option3: "cast",
    option4: "unconformities",
  ),
  MCQ(
    question: "Which of the following animal parts would be most likely to form a fossil?",
    answer: "b",
    option1: "fur ",
    option2: "bornes ",
    option3: "skin",
    option4: "blood",
  ),
  MCQ(
    question: "When minerals take the place of once-living materials, _________ fossils are formed.",
    answer: "d",
    option1: "Physical ",
    option2: "Mold ",
    option3: "Amber",
    option4: "Petrified ",
  ),
  MCQ(
    question: "Fossils are usually found in",
    answer: "a",
    option1: "Sedimentary rocks ",
    option2: "Igneous ",
    option3: "lava ",
    option4: "Metamorphic rocks",
  ),
  MCQ(
    question: "By studying fossils of an animal's ___________, scientists can find out what the animal might have eaten.",
    answer: "b",
    option1: "bones ",
    option2: "droppings ",
    option3: "burrows ",
    option4: "track",
  ),
  MCQ(
    question: "By studying fossils of an animal's ___________, scientists can find out what the animal might have eaten.",
    answer: "a",
    option1: "imprints ",
    option2: "coprolites",
    option3: "molds",
    option4: "trace of fossils",
  ),
  MCQ(
    question: "Which of the following is an example of a trace fossil?",
    answer: "d",
    option1: "skeleton ",
    option2: "trilobites",
    option3: "leaf",
    option4: "footprints",
  ),
  MCQ(
    question: "________ are remains of species that existed on Earth for a relatively short periods of time, were abundant, and were widespread geographically.",
    answer: "c",
    option1: "cast ",
    option2: "uncomformities ",
    option3: "index of fossils ",
    option4: "half lives ",
  ),
  MCQ(
    question:
        "A fossilized dinosaur footprint is an example of",
    answer: "c",
    option1: "a mold",
    option2: "index fossil",
    option3: "a trace fossils",
    option4: "a cast",
  ),
  MCQ(
    question: "A tree buried in a mineral hot spring would probably form a _____________.",
    answer: "b",
    option1: "trace fossils ",
    option2: "petrified fossils ",
    option3: "time scale",
    option4: "mold fossils",
  ),
  
];
